# templates/secrets/docker-credentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
data:
  config.json: {{ .Values.dockerCredentialsConfigJson }}