# templates/secrets/github-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
stringData:
  secret: {{ .Values.githubWebhookSecret | quote }}