# templates/secrets/github-token.yaml
apiVersion: v1
kind: Secret
metadata:
  # Consider parameterizing the name: {{ .Release.Name }}-github
  name: github
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
stringData:
  token: {{ .Values.githubToken | quote }}