apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-ci-pipelines-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/badaiv/argocd-preview-env-demo.git
    path: charts/tekton-ci-pipelines
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      values: |
        githubToken: ghp_xxxxxxxxxxxxxxxxxx
        githubWebhookSecret: "123456"
        dockerCredentialsConfigJson: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-pipelines
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true